### ISSUE TITLE
Some IMU messages are getting skipped

### ISSUE THREAD

**Issue by nonrevlb** [byu-magicc/fcu_io#25] opened 2016-07-07 19:37 UTC
I'm using fcu_io to produce imu messages at 500Hz, but occasionally it is skipping messages.  Below is a matlab generated histogram of the time between imu messages.  At 500Hz, this should be 2 microseconds, but about 1 in 5 times it is skipping a message and getting a difference of 4 microseconds.  

Why are these messages being dropped? Can it be stopped? Or is there at least a way to keep track of when a message gets dropped?

![screenshot from 2016-07-07 13 26 45](https://cloud.githubusercontent.com/assets/13068053/16666857/b9a543c2-4446-11e6-9841-83a9df3837b6.png)

**Comment by dpkoch** [comment] 2016-07-07 19:45
@nonrevlb What branch of fcu_io and ROSflight2 are you using? If you're using master, can you do this test again using the `temperature` branch in ROSflight2 and the `accel_calibration` branch in fcu_io2? The `temperature` branch in ROSflight2 particularly introduces better timing for the IMU timestamps.

**Comment by dpkoch** [comment] 2016-07-07 19:54
This is related to BYU-MAGICC/ROSflight2#37

**Comment by superjax** [comment] 2016-07-07 20:18
This is using the high-quality timestamps of the `temperature` and `accel_calibration` branches.

I think we need to use an o-scope to check the timing of the mavlink stream functions (Using the LED's to send pulses)  It might give us a clue about how MAVlink works and may answer BYU-MAGICC/ROSflight2#22

**Comment by dpkoch** [comment] 2016-07-22 16:44
@nonrevlb I'm unable to reproduce your results from https://github.com/BYU-MAGICC/ROSflight2/issues/22#issuecomment-233729769. When I run the same test, I get the following results:
![image](https://cloud.githubusercontent.com/assets/2702490/17064196/f4b54a82-5000-11e6-8ae4-e1b7001e718e.png)

However, one idea I had is that maybe we're allowing `async_read_some` too big a buffer, and so it collects several IMU messages before returning all of them at the same time (the current buffer size is 256 bytes, which could hold 5+ imu messages). Could you try the test out again using the `timing` branch of fcu_io2?

Also, if it's useful to you, I've created a little python script/ROS node that listens to 1000 imu message and then creates those plots (https://gist.github.com/dpkoch/f0bb47ddeaf03a939fac1b41500f99ed).

**Comment by superjax** [comment] 2016-07-25 23:08
I think that this issue is no longer all that important, as we have gotten the camera driver working without too much here.  It seems that the timing issue was rather an issue of how the image flag was being assigned to the IMU message.

**Closed as completed by superjax** 2016-07-25 23:08 UTC
